/* Einmal ausführen: richtet Sheet, Ordner und Startdaten ein. */
function setupStarten() { return setup(); }

/* GENERATED by build.py from server.js and the prototype seed. Edit those, not this file. */

/* Raum Worship Hub: backend (Google Apps Script, runs as raumworship@gmail.com)
   One Google Sheet is the database. The Sheet and the invoices folder live in a private
   "Raum Leitung" folder, NOT in the shared Raum Worship folder, because every member
   can open the shared folder. */

const P = PropertiesService.getScriptProperties();
const DRIVE_PROTOKOLLE = "REDACTED_ID";
// Drive folder shortcuts for the start page. They live here (not in the public frontend) and reach the app only after login.
const DRIVE_QUICK = []; // REDACTED for the public repo: the 12 Drive folder shortcuts live only in the deployed Apps Script
const INVITE_DAYS = 14;
const MAX_FAILS = 5;
const ROLES = ["leader", "middle", "member"];
const STAGE_KEYS = ["idea","writing","rawdemo","arrangement","production","liverec","mix","release","tbd"];
const STATUS = ["open","prog","done"];

const FIELDS = {
  members:  ["id","name","role","groups","active","invite_hash","invite_expires","token_hashes","updated_at","updated_by","perms","skills","full","avatar","avatar_lg"],
  songs:    ["id","title","stage","rec","leads","writers","key","tempo","meter","cello","gema","ccli","arr","parts","releases","links","note","log","updated_at","updated_by"],
  tasks:    ["id","title","owners","due","status","prio","link","subs","comments","links","updated_at","updated_by","vis"],
  sessions: ["id","date","time","place","pdf","agenda","results","decisions","attendees","rsvp","links","updated_at","updated_by","proto","kind","title","invited"],
  projects: ["id","title","when","note","updated_at","updated_by"],
  ideas:    ["id","title","by","text","memo","date","updated_at","updated_by"],
  prayer:   ["id","kind","by","text","ref","date","pray","reacts","comments","answered","updated_at","updated_by","edited"],
  invoices: ["id","nr","date","vendor","items","amount","status","song","file","updated_at","updated_by"],
  settings: ["key","value"],
  log:      ["at","by","action","entity","id","summary"]
};

/* ---------------- sheet helpers ---------------- */
// opening the Sheet is the slowest call, so each request opens it once and reuses it
let BOOK_ = null, SHEETS_ = {}, TZ_ = null;
function book_() {
  if (BOOK_) return BOOK_;
  const id = P.getProperty("SHEET_ID");
  if (!id) throw err_("not_setup", "Backend ist noch nicht eingerichtet. setup() ausführen.");
  BOOK_ = SpreadsheetApp.openById(id);
  return BOOK_;
}
function sheet_(name) {
  if (SHEETS_[name]) return SHEETS_[name];
  let sh = book_().getSheetByName(name);
  // tabs added after the first setup (e.g. "prayer") are created on first use, as plain text columns
  if (!sh && FIELDS[name] && name !== "avatars") {
    sh = book_().insertSheet(name);
    sh.getRange(1, 1, sh.getMaxRows(), FIELDS[name].length).setNumberFormat("@");
    sh.getRange(1, 1, 1, FIELDS[name].length).setValues([FIELDS[name]]);
    sh.setFrozenRows(1);
  }
  return (SHEETS_[name] = sh);
}
function tz_() { if (!TZ_) { try { TZ_ = book_().getSpreadsheetTimeZone() || "Europe/Berlin"; } catch (e) { TZ_ = "Europe/Berlin"; } } return TZ_; }
function decode_(x) {
  // Sheets turns "2026-10-24" or "19:30" into Date cells even in text columns; turn them back into the plain strings the app stores
  if (Object.prototype.toString.call(x) === "[object Date]") {
    if (isNaN(x.getTime())) return "";
    return Utilities.formatDate(x, tz_(), x.getFullYear() < 1900 ? "HH:mm" : "yyyy-MM-dd");
  }
  if (typeof x === "string") {
    if (x === "TRUE") return true;
    if (x === "FALSE") return false;
    const c = x.charAt(0);
    if (c === "[" || c === "{") { try { return JSON.parse(x); } catch (e) {} }
  }
  return x;
}
function encode_(x) {
  if (x === null || x === undefined) return "";
  if (typeof x === "boolean") return x ? "TRUE" : "FALSE";
  if (typeof x === "object") return JSON.stringify(x);
  return String(x);
}
function readAll_(name) {
  const v = sheet_(name).getDataRange().getValues();
  const h = v[0];
  return v.slice(1).filter(r => r[0] !== "" && r[0] !== null).map(r => {
    const o = {};
    h.forEach((k, i) => { o[k] = decode_(r[i]); });
    return o;
  });
}
function findRow_(name, id) {
  const sh = sheet_(name);
  const ids = sh.getRange(1, 1, Math.max(sh.getLastRow(), 1), 1).getValues();
  for (let i = 1; i < ids.length; i++) if (String(ids[i][0]) === String(id)) return i + 1;
  return -1;
}
function get_(name, id) {
  const r = findRow_(name, id);
  if (r < 0) return null;
  const h = FIELDS[name];
  const v = sheet_(name).getRange(r, 1, 1, h.length).getValues()[0];
  const o = {};
  h.forEach((k, i) => { o[k] = decode_(v[i]); });
  return o;
}
function put_(name, obj) {
  const h = FIELDS[name];
  const row = h.map(k => encode_(obj[k]));
  const sh = sheet_(name);
  if (sh.getLastColumn() < h.length) sh.getRange(1, 1, 1, h.length).setValues([h]);
  let r = findRow_(name, obj[h[0]]);
  if (r < 0) r = sh.getLastRow() + 1;
  sh.getRange(r, 1, 1, h.length).setNumberFormat("@").setValues([row]);  // force plain text so Sheets never converts dates or numbers
  return obj;
}
function del_(name, id) {
  const r = findRow_(name, id);
  if (r > 0) sheet_(name).deleteRow(r);
}
function setting_(key, val) {
  if (val === undefined) {
    const s = readAll_("settings").find(x => x.key === key);
    return s ? s.value : null;
  }
  put_("settings", { key: key, value: val });
}
// large profile pictures do not fit one Sheet cell (50,000 characters), so they are stored in pieces in their own tab
const AVATAR_PART = 45000;
function avatarSheet_() {
  let sh = sheet_("avatars");
  if (!sh) {
    sh = book_().insertSheet("avatars");
    sh.getRange(1, 1, sh.getMaxRows(), 3).setNumberFormat("@");
    sh.getRange(1, 1, 1, 3).setValues([["id", "part", "data"]]);
    SHEETS_["avatars"] = sh;
  }
  return sh;
}
function saveBigAvatar_(id, data) {
  const sh = avatarSheet_();
  const v = sh.getDataRange().getValues();
  for (let i = v.length - 1; i >= 1; i--) if (String(v[i][0]) === id) sh.deleteRow(i + 1);
  for (let p = 0; p * AVATAR_PART < data.length; p++) {
    const r = sh.getLastRow() + 1;
    sh.getRange(r, 1, 1, 3).setNumberFormat("@").setValues([[id, String(p), data.slice(p * AVATAR_PART, (p + 1) * AVATAR_PART)]]);
  }
}
function loadBigAvatar_(id) {
  const sh = sheet_("avatars");
  if (!sh) return "";
  return sh.getDataRange().getValues().slice(1).filter(r => String(r[0]) === id)
    .sort((a, b) => Number(a[1]) - Number(b[1])).map(r => String(r[2])).join("");
}
// leader meeting protocols go into Raum Leitung › Protokolle Leiter Treffen, which only the band account can open
function leitungProtoFolder_() {
  const id = P.getProperty("LEITUNG_PROTO_FOLDER");
  if (id) return DriveApp.getFolderById(id);
  const f = DriveApp.getFolderById(P.getProperty("LEITUNG_FOLDER")).createFolder("Protokolle Leiter Treffen");
  P.setProperty("LEITUNG_PROTO_FOLDER", f.getId());
  return f;
}
// invoice uploads go into the private Rechnungen folder (Raum Leitung), never into the shared band folder
const INVOICE_TYPES = { "application/pdf": "pdf", "image/jpeg": "jpg", "image/png": "png" };
function storeInvoiceFile_(r, up) {
  const ext = INVOICE_TYPES[up && up.mime];
  need_(!!ext, "Bitte PDF, JPG oder PNG hochladen.");
  need_(typeof up.data === "string" && /^[A-Za-z0-9+\/=]+$/.test(up.data) && up.data.length < 12500000, "Datei ist zu groß (höchstens 9 MB).");
  const clean = x => String(x || "").replace(/[^\wäöüÄÖÜß .-]/g, "").trim().slice(0, 40);
  const name = [r.date, clean(r.vendor), clean(r.nr)].filter(Boolean).join("_") + "." + ext;
  const blob = Utilities.newBlob(Utilities.base64Decode(up.data), up.mime, name);
  const file = DriveApp.getFolderById(P.getProperty("INVOICE_FOLDER")).createFile(blob);
  file.setName(name);
  return "drive:" + file.getId();
}
function log_(me, action, entity, id, summary) {
  sheet_("log").appendRow([new Date().toISOString(), me ? me.id : "system", action, entity, id || "", String(summary || "").slice(0, 300)]);
}

/* ---------------- auth ---------------- */
function sha_(s) {
  return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, String(s), Utilities.Charset.UTF_8)
    .map(b => ((b + 256) % 256).toString(16).padStart(2, "0")).join("");
}
function newToken_() { return (Utilities.getUuid() + Utilities.getUuid()).replace(/-/g, ""); }
function newCode_() { let c = ""; for (let i = 0; i < 6; i++) c += Math.floor(Math.random() * 10); return c; }
function err_(code, msg) { const e = new Error(msg); e.code = code; return e; }
function now_() { return new Date().toISOString(); }

function memberByToken_(token) {
  if (!token) throw err_("auth", "Bitte neu anmelden.");
  const h = sha_(token);
  const m = readAll_("members").find(x => x.active !== false && Array.isArray(x.token_hashes) && x.token_hashes.indexOf(h) >= 0);
  if (!m) throw err_("auth", "Anmeldung abgelaufen. Bitte mit deinem Link und Code neu anmelden.");
  return m;
}
const isLeader_ = m => m.role === "leader";
const PRAYER_KINDS = ["impuls", "vers", "anliegen", "dank"];
const PRAYER_EMOJI = ["🙏", "🙌", "❤️", "🔥", "🫶", "✨"];
const canAll_ = m => m.role === "leader" || m.role === "middle";
// leader meetings (kind "leitung") and their private tasks (vis "leaders") exist only for the four leaders
const isLeitung_ = s => !!s && s.kind === "leitung";
const seesSession_ = (s, me) => !isLeitung_(s) || isLeader_(me);
const seesTask_ = (t, me) => !t || t.vis !== "leaders" || isLeader_(me);
const canSongs_ = m => canAll_(m) || (Array.isArray(m.perms) && m.perms.indexOf("songs") >= 0);
function need_(ok, msg) { if (!ok) throw err_("forbidden", msg || "Dafür hast du keine Berechtigung."); }

function makeInvite_(m) {
  const code = newCode_();
  m.invite_hash = sha_(m.id + ":" + code);
  m.invite_expires = new Date(Date.now() + INVITE_DAYS * 864e5).toISOString();
  return code;
}
function inviteLink_(id) {
  const base = P.getProperty("FRONTEND_URL") || "";
  return base ? base.replace(/\/?$/, "/") + "?m=" + encodeURIComponent(id) : "";
}

/* ---------------- public data ---------------- */
function publicMember_(m, viewer) {
  const o = { id: m.id, name: m.name, full: m.full || "", role: m.role, groups: m.groups || [], skills: Array.isArray(m.skills) ? m.skills : [], avatar: m.avatar || "", active: m.active !== false, perms: Array.isArray(m.perms) ? m.perms : [] };
  if (viewer && isLeader_(viewer)) {
    o.invite_expires = m.invite_expires || "";
    o.devices = Array.isArray(m.token_hashes) ? m.token_hashes.length : 0;
  }
  return o;
}
function bootstrap_(me) {
  const data = {
    me: publicMember_(me, me),
    members: readAll_("members").map(m => publicMember_(m, me)),
    songs: readAll_("songs"),
    tasks: readAll_("tasks").filter(t => seesTask_(t, me)),
    sessions: readAll_("sessions").filter(s => seesSession_(s, me)),
    projects: readAll_("projects"),
    ideas: readAll_("ideas"),
    prayer: readAll_("prayer").sort((a, c) => String(c.date).localeCompare(String(a.date))).slice(0, 200),
    money: null,
    vision: null,
    drive: { quick: DRIVE_QUICK },
    server_time: now_()
  };
  const st = {}; readAll_("settings").forEach(x => { st[x.key] = x.value; });
  data.vision = st.vision && typeof st.vision === "object" ? st.vision : null;
  // finances are open for every member to read (transparency, decided 09.10.); only leaders change them
  data.money = { start: Number(st.start_balance || 0), startNote: st.start_note || "", invoices: readAll_("invoices").map(r => Object.assign(r, { amount: Number(r.amount || 0) })) };
  return data;
}

/* ---------------- concurrency ---------------- */
function checkBase_(current, base) {
  // an existing record may only be changed by someone who saw its current version; no base means "create new", never "overwrite"
  if (current && (base === undefined || base === null || base === ""))
    throw err_("conflict", "Diese ID gibt es schon. Bitte neu laden und den vorhandenen Eintrag bearbeiten.");
  if (current && String(current.updated_at) !== String(base))
    throw err_("conflict", "Jemand hat das gerade geändert. Die App lädt den neuen Stand.");
}
function stamp_(o, me) { o.updated_at = now_(); o.updated_by = me.id; return o; }
function cleanStatus_(s) { return STATUS.indexOf(s) >= 0 ? s : "open"; }

/* ---------------- actions ---------------- */
const ACTIONS = {
  ping: () => ({ service: "raum-worship-hub", time: now_() }),
  names: () => readAll_("members").filter(m => m.active !== false).map(m => ({ id: m.id, name: m.name })),

  login: (b) => {
    const id = String(b.member || "");
    const code = String(b.code || "").replace(/\D/g, "");
    const cache = CacheService.getScriptCache();
    const key = "fail_" + id;
    const fails = Number(cache.get(key) || 0);
    if (fails >= MAX_FAILS) throw err_("locked", "Zu viele falsche Versuche. Bitte in 15 Minuten nochmal.");
    const m = get_("members", id);
    const ok = m && m.active !== false && m.invite_hash && m.invite_hash === sha_(id + ":" + code) && new Date(m.invite_expires) > new Date();
    if (!ok) {
      cache.put(key, String(fails + 1), 900);
      throw err_("bad_code", "Code stimmt nicht oder ist abgelaufen. Frag die Leitung nach einem neuen Code.");
    }
    cache.remove(key);
    const token = newToken_();
    const hashes = (Array.isArray(m.token_hashes) ? m.token_hashes : []).concat([sha_(token)]).slice(-6);
    m.token_hashes = hashes;
    put_("members", m);
    log_(m, "login", "members", m.id, "Gerät angemeldet");
    return { token: token, data: bootstrap_(m) };
  },

  bootstrap: (b, me) => bootstrap_(me),

  logout: (b, me) => {
    const m = get_("members", me.id);
    const h = sha_(b.token);
    m.token_hashes = (m.token_hashes || []).filter(x => x !== h);
    put_("members", m);
    return { done: true };
  },

  /* songs */
  saveSong: (b, me) => {
    need_(canSongs_(me));
    const s = b.song || {};
    need_(s.id && s.title, "Song braucht eine ID und einen Titel.");
    const cur = get_("songs", s.id);
    checkBase_(cur, b.base);
    if (STAGE_KEYS.indexOf(s.stage) < 0) s.stage = "idea";
    if (cur && (cur.gema || cur.ccli) && !isLeader_(me)) s.writers = cur.writers;
    if (cur && JSON.stringify(cur.writers) !== JSON.stringify(s.writers)) {
      s.log = (cur.log || []).concat([{ v: (s.writers || []).join(", "), by: me.id, at: now_().slice(0, 10) }]);
    } else if (cur) s.log = cur.log || [];
    if (!isLeader_(me) && cur) { s.gema = cur.gema; s.ccli = cur.ccli; }
    put_("songs", stamp_(s, me));
    log_(me, cur ? "update" : "create", "songs", s.id, s.title + " · " + s.stage);
    return s;
  },

  songOp: (b, me) => {
    const s = get_("songs", b.id);
    need_(!!s, "Song nicht gefunden.");
    const all = canSongs_(me);
    if (b.op === "partStatus") {
      const p = (s.parts || []).find(x => x.key === b.key);
      need_(!!p, "Part nicht gefunden.");
      const mine = p.owner === me.id || (Array.isArray(p.co) && p.co.indexOf(me.id) >= 0);
      need_(all || mine, "Nur die Zuständigen oder die Leitung können diesen Part ändern.");
      p.status = cleanStatus_(b.status);
      if (b.note !== undefined && (all || mine)) p.note = String(b.note).slice(0, 200);
    } else if (b.op === "arr") {
      need_(b.track === "v" || b.track === "i", "Unbekannter Arrangement Teil.");
      const owners = b.track === "v" ? (s.leads || []) : ((s.arr && s.arr.io) || []);
      need_(all || owners.indexOf(me.id) >= 0, "Nur die Zuständigen oder die Leitung.");
      s.arr = s.arr || {};
      s.arr[b.track] = cleanStatus_(b.status);
    } else if (b.op === "writers") {
      need_(!(s.gema || s.ccli) || isLeader_(me), "Gesperrt, weil registriert. Nur Leitung kann ändern.");
      const w = (b.writers || []).map(x => String(x).slice(0, 60)).slice(0, 12);
      s.writers = w;
      s.log = (s.log || []).concat([{ v: w.join(", "), by: me.id, at: now_().slice(0, 10) }]);
    } else if (b.op === "addLink") {
      const u = String(b.url || "");
      need_(/^https:\/\//.test(u), "Link muss mit https:// beginnen.");
      s.links = (s.links || []).concat([{ l: String(b.label || "Link").slice(0, 80), u: u.slice(0, 500), by: me.id }]);
    } else if (b.op === "delLink") {
      const l = (s.links || [])[b.index];
      need_(!!l, "Link nicht gefunden.");
      need_(all || l.by === me.id, "Nur wer den Link angelegt hat oder die Leitung.");
      s.links.splice(b.index, 1);
    } else throw err_("bad_request", "Unbekannte Aktion.");
    put_("songs", stamp_(s, me));
    log_(me, "songOp:" + b.op, "songs", s.id, s.title);
    return s;
  },

  deleteSong: (b, me) => { need_(isLeader_(me)); del_("songs", b.id); log_(me, "delete", "songs", b.id, ""); return { done: true }; },

  /* tasks */
  saveTask: (b, me) => {
    const t = b.task || {};
    need_(t.id && t.title, "Aufgabe braucht einen Titel.");
    const cur = get_("tasks", t.id);
    need_(seesTask_(cur, me), "Aufgabe nicht gefunden.");
    if (!isLeader_(me)) t.vis = cur ? (cur.vis || "") : "";
    else t.vis = t.vis === "leaders" ? "leaders" : "";
    // a private leader task becomes visible as soon as someone outside the leadership is responsible for it
    if (t.vis === "leaders") { const lead = readAll_("members").filter(m => m.role === "leader").map(m => m.id); if ((t.owners || []).some(o => lead.indexOf(o) < 0)) t.vis = ""; }
    if (cur) {
      need_(canAll_(me) || (cur.owners || []).indexOf(me.id) >= 0, "Nur Zuständige oder Leitung können diese Aufgabe ändern.");
      checkBase_(cur, b.base);
      if (!canAll_(me)) t.owners = cur.owners;
      t.comments = cur.comments || [];
    } else {
      if (!canAll_(me)) t.owners = [me.id];
      t.comments = [];
    }
    t.status = cleanStatus_(t.status);
    put_("tasks", stamp_(t, me));
    log_(me, cur ? "update" : "create", "tasks", t.id, t.title + " · " + t.status);
    return t;
  },
  commentTask: (b, me) => {
    const t = get_("tasks", b.id);
    need_(!!t && seesTask_(t, me), "Aufgabe nicht gefunden.");
    const text = String(b.text || "").trim().slice(0, 1000);
    need_(!!text, "Kommentar ist leer.");
    t.comments = (t.comments || []).concat([{ by: me.id, text: text, at: now_().slice(0, 10) }]);
    put_("tasks", stamp_(t, me));
    log_(me, "comment", "tasks", t.id, text.slice(0, 60));
    return t;
  },
  deleteTask: (b, me) => { need_(canAll_(me)); need_(seesTask_(get_("tasks", b.id), me), "Aufgabe nicht gefunden."); del_("tasks", b.id); log_(me, "delete", "tasks", b.id, ""); return { done: true }; },

  /* sessions */
  // leaders can remove a meeting that was created by mistake, as long as no protocol exists yet
  deleteSession: (b, me) => {
    need_(isLeader_(me), "Treffen löscht nur die Leitung.");
    const s = get_("sessions", b.id);
    need_(!!s && seesSession_(s, me), "Treffen nicht gefunden.");
    need_(!s.pdf && !(s.proto && s.proto.groups && s.proto.groups.some(g => g.note || (g.items || []).length)), "Zu diesem Treffen gibt es schon ein Protokoll.");
    del_("sessions", s.id);
    log_(me, "delete", "sessions", s.id, s.date);
    return { done: true };
  },
  rsvp: (b, me) => {
    const s = get_("sessions", b.id);
    need_(!!s && seesSession_(s, me), "Session nicht gefunden.");
    need_(["yes","no","maybe"].indexOf(b.v) >= 0, "Ungültige Antwort.");
    need_(s.kind !== "gruppe" || (s.invited || []).indexOf(me.id) >= 0, "Zu diesem Treffen bist du nicht eingeladen.");
    s.rsvp = s.rsvp || {};
    s.rsvp[me.id] = b.v;
    put_("sessions", stamp_(s, me));
    return s;
  },
  saveSession: (b, me) => {
    need_(canAll_(me));
    const s = b.session || {};
    need_(s.id && s.date, "Session braucht ein Datum.");
    const cur = get_("sessions", s.id);
    // kind is fixed once a meeting exists: "" creative session, "leitung" leader meeting, "gruppe" meeting with a few invited members
    s.kind = cur ? (cur.kind || "") : (["leitung", "gruppe"].indexOf(s.kind) >= 0 ? s.kind : "");
    need_(seesSession_(cur, me) && (!s.kind || isLeader_(me)), s.kind === "gruppe" ? "Treffen mit Einladung verwaltet die Leitung." : "Leiter Treffen verwaltet nur die Leitung.");
    s.title = String(s.title || "").trim().slice(0, 80);
    if (s.kind === "gruppe") {
      const ids = readAll_("members").map(m => m.id);
      s.invited = (Array.isArray(s.invited) ? s.invited : []).filter((x, i, a) => ids.indexOf(x) >= 0 && a.indexOf(x) === i);
      need_(s.title, "Das Treffen braucht einen Namen.");
      need_(s.invited.length > 0, "Lade mindestens eine Person ein.");
    } else s.invited = [];
    checkBase_(cur, b.base);
    if (cur) s.rsvp = cur.rsvp || {};
    put_("sessions", stamp_(s, me));
    log_(me, cur ? "update" : "create", "sessions", s.id, s.date);
    return s;
  },
  // protocol written in the app: saves the session protocol and turns every task row into a real task in one step
  saveProtocol: (b, me) => {
    need_(canAll_(me), "Protokolle schreibt die Leitung.");
    const cur = get_("sessions", b.id);
    need_(!!cur && seesSession_(cur, me), "Session nicht gefunden.");
    checkBase_(cur, b.base);
    const all = readAll_("members");
    const ids = all.map(m => m.id);
    const leaders = all.filter(m => m.role === "leader").map(m => m.id);
    const txt = (x, n) => String(x || "").slice(0, n);
    const p = b.proto || {};
    const STAT = ["open", "prog", "done"];
    cur.proto = {
      writer: ids.indexOf(p.writer) >= 0 ? p.writer : me.id,
      info: txt(p.info, 6000),
      review: txt(p.review, 4000),
      groups: (Array.isArray(p.groups) ? p.groups : []).slice(0, 20).map(g => ({ t: txt(g.t, 80), who: txt(g.who, 200), status: STAT.indexOf(g.status) >= 0 ? g.status : "open", note: txt(g.note, 300) })).filter(g => g.t)
    };
    if (Array.isArray(b.attendees)) cur.attendees = b.attendees.filter(x => ids.indexOf(x) >= 0);
    if (b.agenda !== undefined) cur.agenda = txt(b.agenda, 4000);
    put_("sessions", stamp_(cur, me));
    const made = [];
    (Array.isArray(b.newTasks) ? b.newTasks : []).slice(0, 30).forEach((x, i) => {
      const title = txt(x.title, 160).trim();
      if (!title) return;
      const owners = (Array.isArray(x.owners) ? x.owners : []).filter(o => ids.indexOf(o) >= 0);
      const due = /^\d{4}-\d{2}-\d{2}$/.test(String(x.due || "")) ? x.due : "";
      const own = owners.length ? owners : [me.id];
      // a task from a leader meeting stays private unless someone outside the leadership has to do it
      const vis = isLeitung_(cur) && own.every(o => leaders.indexOf(o) >= 0) ? "leaders" : "";
      const t = { id: "t" + Date.now() + "_" + i, title: title, owners: own, due: due, status: "open", prio: "mid", link: { type: "session", id: cur.id }, subs: [], comments: [], links: [], vis: vis };
      put_("tasks", stamp_(t, me));
      made.push(t);
    });
    log_(me, "saveProtocol", "sessions", cur.id, made.length + " neue Aufgaben");
    return { session: cur, tasks: made };
  },
  exportProtocol: (b, me) => {
    need_(canAll_(me));
    const s = get_("sessions", b.id);
    need_(!!s && seesSession_(s, me), "Session nicht gefunden.");
    const lt = isLeitung_(s);
    const gr = s.kind === "gruppe";
    const sameKind = x => (x.kind || "") === (s.kind || "") && (!gr || x.title === s.title);
    const fileBase = lt ? "Protokoll_Leiter_Treffen_" : gr ? "Protokoll_" + String(s.title || "Treffen").replace(/[^\wäöüÄÖÜß ]+/g, "").trim().replace(/\s+/g, "_") + "_" : "Protokoll_";
    const members = readAll_("members");
    const nm = id => (members.find(m => m.id === id) || { name: id }).name;
    const de = x => x ? String(x).split("-").reverse().join(".") : "";
    const p = s.proto || {};
    const d = de(s.date);
    const doc = DocumentApp.create(fileBase + d);
    const body = doc.getBody();
    const H = DocumentApp.ParagraphHeading;
    body.appendParagraph(lt ? "Protokoll Leiter Treffen (vertraulich)" : gr ? "Protokoll " + (s.title || "Treffen") : "Protokoll Creative Session").setHeading(H.HEADING1);
    const att = (s.attendees && s.attendees.length) ? s.attendees : Object.keys(s.rsvp || {}).filter(k => s.rsvp[k] === "yes");
    body.appendTable([["Datum", d], ["Uhrzeit", s.time || ""], ["Ort", s.place || ""], ["Protokoll geführt von", nm(p.writer || "ricsi")], ["Anwesende", att.map(nm).join(", ")]]);
    // a line starting with spaces or "o " becomes a sub point, like in Richard's protocols
    const bullets = text => {
      const lines = String(text || "").split("\n").filter(l => l.trim());
      if (!lines.length) { body.appendParagraph("Keine Einträge."); return; }
      lines.forEach(l => {
        const sub = /^(\s{2,}|\t|o\s)/.test(l);
        body.appendListItem(l.replace(/^\s*([•\-*o]\s+)?/, "")).setNestingLevel(sub ? 1 : 0);
      });
    };
    body.appendParagraph("1. Allgemeine Infos").setHeading(H.HEADING2); bullets(p.info);
    body.appendParagraph("2. Review letztes Treffen").setHeading(H.HEADING2); bullets(p.review);
    body.appendParagraph("3. Heutiges Treffen: Aufgaben und Zuständigkeiten").setHeading(H.HEADING2);
    const st = x => x === "done" ? "erledigt" : x === "prog" ? "in Bearbeitung" : "offen";
    const groups = p.groups || [];
    if (groups.length) body.appendTable([["Aufgabe / Thema", "Zuständig", "Status", "Notizen / Termin"]].concat(groups.map(g => [g.t, g.who, st(g.status), g.note || ""])));
    else body.appendParagraph("Keine Einträge.");
    // open tasks, plus everything finished since the previous session
    const prev = readAll_("sessions").filter(x => sameKind(x) && x.date < s.date).sort((a, c) => c.date.localeCompare(a.date))[0];
    const since = prev ? prev.date : "0000";
    const tasks = readAll_("tasks").filter(t => (lt || t.vis !== "leaders") && (t.status !== "done" || String(t.updated_at || "").slice(0, 10) >= since))
      .sort((a, c) => (a.status === "done") - (c.status === "done") || String(a.due || "9999").localeCompare(String(c.due || "9999")));
    body.appendParagraph("4. Offene To-dos").setHeading(H.HEADING2);
    body.appendTable([["To-do", "Verantwortlich", "Fällig bis", "Status"]].concat(tasks.map(t => [t.title, (t.owners || []).map(nm).join(", "), de(t.due), st(t.status)])));
    const next = readAll_("sessions").filter(x => sameKind(x) && x.date > s.date).sort((a, c) => a.date.localeCompare(c.date))[0];
    body.appendParagraph("5. Nächstes Treffen").setHeading(H.HEADING2);
    body.appendTable(next ? [["Datum", "Uhrzeit", "Ort"], [de(next.date), next.time || "", next.place || ""]] : [["Noch kein Termin"]]);
    doc.saveAndClose();
    const folder = lt ? leitungProtoFolder_() : DriveApp.getFolderById(DRIVE_PROTOKOLLE);
    const pdf = folder.createFile(doc.getAs("application/pdf")).setName(fileBase + d + ".pdf");
    DriveApp.getFileById(doc.getId()).setTrashed(true);
    s.pdf = pdf.getId();
    put_("sessions", stamp_(s, me));
    log_(me, "exportProtocol", "sessions", s.id, pdf.getName());
    return s;
  },

  /* ideas and projects */
  addIdea: (b, me) => {
    const title = String(b.title || "").trim().slice(0, 120);
    need_(!!title, "Idee braucht einen Titel.");
    const i = { id: "i" + Date.now(), title: title, by: me.id, text: String(b.text || "").slice(0, 4000), memo: String(b.memo || ""), date: now_().slice(0, 10) };
    put_("ideas", stamp_(i, me));
    log_(me, "create", "ideas", i.id, title);
    return i;
  },
  /* prayer and spiritual input: everyone can share, react and comment; the author or a leader can delete */
  addPrayer: (b, me) => {
    const kind = PRAYER_KINDS.indexOf(b.kind) >= 0 ? b.kind : "impuls";
    const text = String(b.text || "").trim().slice(0, 6000);
    need_(!!text, "Bitte etwas schreiben.");
    const by = me.id;   // everyone posts only in their own name (no posting on behalf of others)
    const p = { id: "g" + Date.now() + "_" + Math.floor(Math.random() * 1000), kind: kind, by: by, text: text, ref: String(b.ref || "").trim().slice(0, 120), date: now_(), pray: [], reacts: {}, comments: [], answered: false };
    put_("prayer", stamp_(p, me));
    log_(me, "create", "prayer", p.id, kind);
    return p;
  },
  reactPrayer: (b, me) => {
    const p = get_("prayer", b.id);
    need_(!!p, "Beitrag nicht gefunden.");
    if (b.pray) {
      const l = Array.isArray(p.pray) ? p.pray : [];
      p.pray = l.indexOf(me.id) >= 0 ? l.filter(x => x !== me.id) : l.concat([me.id]);
    } else {
      need_(PRAYER_EMOJI.indexOf(b.emoji) >= 0, "Unbekannte Reaktion.");
      const r = p.reacts && typeof p.reacts === "object" ? p.reacts : {};
      const l = Array.isArray(r[b.emoji]) ? r[b.emoji] : [];
      r[b.emoji] = l.indexOf(me.id) >= 0 ? l.filter(x => x !== me.id) : l.concat([me.id]);
      if (!r[b.emoji].length) delete r[b.emoji];
      p.reacts = r;
    }
    put_("prayer", stamp_(p, me));
    return p;
  },
  commentPrayer: (b, me) => {
    const p = get_("prayer", b.id);
    need_(!!p, "Beitrag nicht gefunden.");
    const text = String(b.text || "").trim().slice(0, 1000);
    need_(!!text, "Kommentar ist leer.");
    p.comments = (Array.isArray(p.comments) ? p.comments : []).concat([{ by: me.id, text: text, at: now_() }]).slice(-100);
    put_("prayer", stamp_(p, me));
    return p;
  },
  answeredPrayer: (b, me) => {
    const p = get_("prayer", b.id);
    need_(!!p, "Beitrag nicht gefunden.");
    need_(p.by === me.id || isLeader_(me), "Nur wer das Anliegen geteilt hat, kann es als erhört markieren.");
    p.answered = !p.answered;
    put_("prayer", stamp_(p, me));
    return p;
  },
  // only the author edits a post, so nobody's words are changed in their name
  editPrayer: (b, me) => {
    const p = get_("prayer", b.id);
    need_(!!p, "Beitrag nicht gefunden.");
    need_(p.by === me.id, "Bearbeiten kann nur, wer es geteilt hat.");
    const text = String(b.text || "").trim().slice(0, 6000);
    need_(!!text, "Bitte etwas schreiben.");
    p.text = text;
    if (b.ref !== undefined) p.ref = String(b.ref || "").trim().slice(0, 120);
    if (PRAYER_KINDS.indexOf(b.kind) >= 0) p.kind = b.kind;
    p.edited = now_();
    put_("prayer", stamp_(p, me));
    log_(me, "update", "prayer", p.id, p.kind);
    return p;
  },
  deletePrayer: (b, me) => {
    const p = get_("prayer", b.id);
    need_(!!p, "Beitrag nicht gefunden.");
    need_(p.by === me.id || isLeader_(me), "Löschen kann nur, wer es geteilt hat, oder die Leitung.");
    del_("prayer", p.id);
    log_(me, "delete", "prayer", p.id, p.kind);
    return { done: true };
  },
  promoteIdea: (b, me) => {
    need_(canAll_(me));
    const i = get_("ideas", b.id);
    need_(!!i, "Idee nicht gefunden.");
    const s = { id: "s" + Date.now(), title: i.title, stage: "idea", rec: "studio", leads: [], writers: [i.by], key: "", tempo: "", meter: "", cello: false, gema: false, ccli: false,
      arr: { v: "open", i: "open" }, parts: stdParts({}), releases: [], links: i.memo ? [{ l: "Sprachmemo", u: i.memo, by: i.by }] : [], note: i.text || "", log: [] };
    put_("songs", stamp_(s, me));
    del_("ideas", i.id);
    log_(me, "promote", "ideas", i.id, i.title);
    return s;
  },
  saveProject: (b, me) => {
    need_(canAll_(me));
    const p = b.project || {};
    need_(p.id && p.title, "Projekt braucht einen Titel.");
    put_("projects", stamp_(p, me));
    return p;
  },

  /* money: leaders only */
  saveInvoice: (b, me) => {
    need_(isLeader_(me), "Finanzen sind nur für die Leitung.");
    const r = b.invoice || {};
    need_(r.id && r.vendor && r.date, "Rechnung braucht Absender und Datum.");
    r.amount = Number(r.amount || 0);
    r.status = r.status === "open" ? "open" : "paid";
    const cur = get_("invoices", r.id);
    checkBase_(cur, b.base);
    if (b.upload) r.file = storeInvoiceFile_(r, b.upload);
    else if (cur && /^drive:/.test(String(cur.file || ""))) r.file = cur.file;   // never lose an uploaded file on a status change
    else if (/^drive:/.test(String(r.file || ""))) r.file = "";             // drive: references are only ever set by an upload
    put_("invoices", stamp_(r, me));
    log_(me, cur ? "update" : "create", "invoices", r.id, r.vendor + " " + r.amount);
    return r;
  },
  getProtocolFile: (b, me) => {
    need_(isLeader_(me), "Nur für die Leitung.");
    const s = get_("sessions", b.id);
    need_(isLeitung_(s) && !!s.pdf, "Kein Protokoll hinterlegt.");
    const f = DriveApp.getFileById(String(s.pdf));
    return { name: f.getName(), mime: f.getMimeType(), data: Utilities.base64Encode(f.getBlob().getBytes()) };
  },
  getInvoiceFile: (b, me) => {
    need_(isLeader_(me), "Finanzen sind nur für die Leitung.");
    const r = get_("invoices", b.id);
    need_(!!r && /^drive:[\w-]+$/.test(String(r.file || "")), "Keine Datei hinterlegt.");
    const f = DriveApp.getFileById(String(r.file).slice(6));
    return { name: f.getName(), mime: f.getMimeType(), data: Utilities.base64Encode(f.getBlob().getBytes()) };
  },
  deleteInvoice: (b, me) => { need_(isLeader_(me)); del_("invoices", b.id); log_(me, "delete", "invoices", b.id, ""); return { done: true }; },
  setAvatar: (b, me) => {
    const id = b.id || me.id;
    need_(id === me.id || isLeader_(me), "Nur das eigene Bild oder die Leitung.");
    const img = String(b.image || "");
    need_(img === "" || (/^data:image\/jpeg;base64,[A-Za-z0-9+\/=]+$/.test(img) && img.length < 45000), "Bild bitte als kleines JPEG.");
    const m = get_("members", id);
    need_(!!m, "Mitglied nicht gefunden.");
    const big = String(b.large || "");
    need_(big === "" || (/^data:image\/jpeg;base64,[A-Za-z0-9+\/=]+$/.test(big) && big.length < 420000), "Großes Bild bitte als JPEG unter 420.000 Zeichen.");
    m.avatar = img;
    m.avatar_lg = "";
    put_("members", stamp_(m, me));
    saveBigAvatar_(id, img ? big : "");
    log_(me, "setAvatar", "members", id, img ? "neues Bild" : "Bild entfernt");
    return publicMember_(m, me);
  },
  getAvatar: (b, me) => {
    const m = get_("members", b.id);
    need_(!!m, "Mitglied nicht gefunden.");
    return { id: m.id, image: loadBigAvatar_(m.id) || m.avatar_lg || m.avatar || "" };
  },
  saveVision: (b, me) => {
    need_(isLeader_(me), "Die Vision pflegt nur die Leitung.");
    const v = b.vision;
    need_(v && typeof v === "object" && Array.isArray(v.sections), "Vision braucht Abschnitte.");
    need_(JSON.stringify(v).length < 40000, "Vision ist zu lang.");
    setting_("vision", v);
    log_(me, "saveVision", "settings", "vision", v.sections.length + " Abschnitte");
    return { done: true };
  },
  setStartBalance: (b, me) => {
    need_(isLeader_(me));
    setting_("start_balance", Number(b.value || 0));
    if (b.note !== undefined) setting_("start_note", String(b.note));
    return { done: true };
  },

  /* members: leaders only */
  saveMember: (b, me) => {
    need_(isLeader_(me), "Mitglieder verwaltet nur die Leitung.");
    const m = b.member || {};
    need_(m.id && m.name, "Mitglied braucht einen Namen.");
    need_(ROLES.indexOf(m.role) >= 0, "Unbekannte Rolle.");
    const cur = get_("members", m.id) || {};
    const list = (a, n, len) => (Array.isArray(a) ? a : []).map(x => String(x).trim().slice(0, len)).filter(Boolean).slice(0, n);
    const o = Object.assign({}, cur, { id: m.id, name: m.name, role: m.role, groups: list(m.groups, 12, 60), active: m.active !== false, perms: (m.perms || []).filter(x => x === "songs") });
    if (m.skills !== undefined) o.skills = list(m.skills, 12, 80);
    if (m.full !== undefined) o.full = String(m.full || "").trim().slice(0, 60);
    if (o.active === false) o.token_hashes = [];
    put_("members", stamp_(o, me));
    log_(me, "saveMember", "members", o.id, o.name + " · " + o.role);
    return publicMember_(o, me);
  },
  invite: (b, me) => {
    need_(isLeader_(me), "Einladungen verschickt nur die Leitung.");
    const m = get_("members", b.id);
    need_(!!m, "Mitglied nicht gefunden.");
    const code = makeInvite_(m);
    put_("members", stamp_(m, me));
    log_(me, "invite", "members", m.id, "neuer Code");
    return { id: m.id, name: m.name, code: code, link: inviteLink_(m.id), expires: m.invite_expires };
  }
};
const WRITE_ACTIONS = ["login","logout","saveSong","songOp","deleteSong","saveTask","commentTask","deleteTask","rsvp","saveSession","deleteSession","saveProtocol","exportProtocol","addIdea","promoteIdea","saveProject","saveInvoice","deleteInvoice","setStartBalance","saveVision","setAvatar","addPrayer","reactPrayer","commentPrayer","answeredPrayer","editPrayer","deletePrayer","saveMember","invite"];
const PUBLIC_ACTIONS = ["ping","login","names"];

/* ---------------- HTTP ---------------- */
function handle_(body) {
  const action = body && body.action;
  const fn = ACTIONS[action];
  if (!fn) return { ok: false, error: "bad_request", message: "Unbekannte Aktion." };
  const write = WRITE_ACTIONS.indexOf(action) >= 0;
  const lock = write ? LockService.getScriptLock() : null;
  try {
    if (lock) lock.waitLock(20000);
    const me = PUBLIC_ACTIONS.indexOf(action) >= 0 ? null : memberByToken_(body.token);
    return { ok: true, data: fn(body, me) };
  } catch (e) {
    return { ok: false, error: e.code || "server", message: e.code ? e.message : "Serverfehler: " + e.message };
  } finally {
    if (lock) try { lock.releaseLock(); } catch (e) {}
  }
}
function json_(o) { return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON); }
function doGet() { return json_({ ok: true, data: ACTIONS.ping() }); }
function doPost(e) {
  let body = {};
  try { body = JSON.parse((e && e.postData && e.postData.contents) || "{}"); }
  catch (x) { return json_({ ok: false, error: "bad_request", message: "Ungültige Anfrage." }); }
  return json_(handle_(body));
}

/* ---------------- one time setup (run by hand in the editor) ---------------- */
function setup() {
  if (P.getProperty("SHEET_ID")) throw new Error("Schon eingerichtet. Nichts wurde verändert. SHEET_ID: " + P.getProperty("SHEET_ID"));
  const leitung = DriveApp.createFolder("Raum Leitung");
  const rechnungen = leitung.createFolder("Rechnungen");
  const book = SpreadsheetApp.create("Raum Worship Hub Daten");
  DriveApp.getFileById(book.getId()).moveTo(leitung);
  Object.keys(FIELDS).forEach((name, i) => {
    const sh = i === 0 ? book.getSheets()[0].setName(name) : book.insertSheet(name);
    sh.getRange(1, 1, sh.getMaxRows(), FIELDS[name].length).setNumberFormat("@");
    sh.getRange(1, 1, 1, FIELDS[name].length).setValues([FIELDS[name]]).setFontWeight("bold");
    sh.setFrozenRows(1);
  });
  P.setProperties({ SHEET_ID: book.getId(), LEITUNG_FOLDER: leitung.getId(), INVOICE_FOLDER: rechnungen.getId() });

  const D = seed();
  const sys = { id: "setup" };
  D.ideas = [];                                   // the prototype example idea is not real data
  D.sessions.forEach(s => { s.rsvp = {}; });      // prototype sample answers are not real
  D.members.forEach(m => { m.active = true; m.token_hashes = []; put_("members", stamp_(m, sys)); });
  D.songs.forEach(s => put_("songs", stamp_(s, sys)));
  D.tasks.forEach(t => put_("tasks", stamp_(t, sys)));
  D.sessions.forEach(s => put_("sessions", stamp_(s, sys)));
  D.projects.forEach(p => put_("projects", stamp_(p, sys)));
  D.money.invoices.forEach(r => put_("invoices", stamp_(r, sys)));
  setting_("start_balance", D.money.start);
  setting_("start_note", D.money.startNote);

  const oti = get_("members", "oti");
  const code = makeInvite_(oti);
  put_("members", oti);
  log_(null, "setup", "all", "", "Sheet, Ordner und Startdaten angelegt");
  Logger.log("Fertig. Sheet: " + book.getUrl());
  Logger.log("Ordner Raum Leitung: " + leitung.getUrl());
  Logger.log("Erster Code für Oti (14 Tage gültig): " + code);
  return { sheet: book.getUrl(), code: code };
}

/* Set the GitHub Pages address once it exists (step 3). */
/* one time, run by hand in the editor: shared folder "Raum Leiter Ablage" for the four leaders (edit rights),
   with the invoice folder and the leader meeting protocols moved inside. The database stays in the private "Raum Leitung". */
const LEADER_EMAILS = []; // REDACTED for the public repo: the four leader addresses live only in the deployed Apps Script
function leiterAblageEinrichten() {
  let id = P.getProperty("LEADER_SHARE_FOLDER");
  const ablage = id ? DriveApp.getFolderById(id) : DriveApp.createFolder("Raum Leiter Ablage");
  P.setProperty("LEADER_SHARE_FOLDER", ablage.getId());
  DriveApp.getFolderById(P.getProperty("INVOICE_FOLDER")).moveTo(ablage);
  leitungProtoFolder_().moveTo(ablage);
  const out = [];
  LEADER_EMAILS.forEach(e => { try { ablage.addEditor(e); out.push("OK " + e); } catch (x) { out.push("FEHLER " + e + ": " + x.message); } });
  Logger.log("Ordner: " + ablage.getUrl() + "\n" + out.join("\n"));
  return out;
}
/* one time, run by hand: move Claude's two test uploads of 09.10.2026 to the trash */
function testdateienAufraeumen() {
  const out = [];
  ["Protokoll_24.10.2026.pdf", "2026-10-09_TEST Upload Claude_0.pdf"].forEach(n => { const it = DriveApp.getFilesByName(n); let k = 0; while (it.hasNext()) { const f = it.next(); f.setTrashed(true); k++; } out.push(n + ": " + k + " im Papierkorb"); });
  Logger.log(out.join("\n"));
  return out;
}
function setFrontendUrl(url) { P.setProperty("FRONTEND_URL", url); }


/* ---------------- start data (same as the approved prototype, 08.10.2026) ---------------- */
const STD_PARTS=[["drums","Drums","oti"],["percs","Percs","oti"],["bass","Bass","fini"],["synth","Synth","jeremy"],["egit","E-Gitarren",""],["acoustic","Akustik",""],["piano","Piano",""],["keys","Keys",""],["cello","Cello","suli"]];
function stdParts(o){return STD_PARTS.map(([key,name,owner])=>Object.assign({key,name,owner,status:"open",note:"",ext:false},o[key]||{}))}
function seed(){ /* REDACTED for the public repo: band members, songs, tasks and Drive links of the start data live only in the deployed Apps Script */ return {}; }
